### ISSUE TITLE
No traffic on download

### ISSUE THREAD

**Issue by subversive-owl** [ratpoison-io/leaf-examples#10]
When I run the `load-dataset` command, I don't get an error, but I don't get any incoming traffic.

Example from running `sudo nethogs`:

```
 9336 user     target/debug/juice-examples tun0       0.000       0.000 KB/sec
```

```
    Finished dev [unoptimized + debuginfo] target(s) in 7.89 secs
     Running `target/debug/juice-examples load-dataset fashion`
Downloading... 1/4: train-images-idx3-ubyte.gz
URL: http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/train-images-idx3-ubyte.gz
```

This happens with the MNIST set too. I have to use `wget` to deposit the files in the folder manually.

**Comment by drahnr** [comment]
It appears the remote moved and returns a `301`, and that seems to stall the `.wait()` routine stalls. Reading the `301` header it moved to `https`. Please checkout the pending PR.

**Comment by subversive-owl** [comment]
That PR fixes my problem with downloads, but I get this on run with MNIST:

```
env RUST_BACKTRACE=1 ./target/release/juice-examples mnist conv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UninitializedMemory', /checkout/src/libcore/result.rs:860
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
  10: <juice::layers::common::convolution::Convolution<B> as juice::layer::ComputeOutput<f32, B>>::compute_output
  11: juice::layer::ILayer::forward
  12: <juice::layer::Layer<B>>::forward
  13: <juice::layers::container::sequential::Sequential<B> as juice::layer::ILayer<B>>::forward
  14: <juice::layer::Layer<B>>::forward
  15: <juice::solver::Solver<SolverB, B>>::train_minibatch
  16: juice_examples::run_mnist
  17: juice_examples::main
  18: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  19: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  20: __libc_start_main
  21: _start
```
