### ISSUE TITLE
CUDA API change?

### ISSUE THREAD

**Issue by lake-effect** [ratpoison-io/leaf-examples#20]
```
./target/release/juice-examples fashion conv
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotInitialized("CUDA Driver/Runtime API not initialized.")', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

```
  8: core::result::unwrap_failed
   9: std::sync::once::Once::call_once::{{closure}}
  10: std::sync::once::Once::call_inner
             at libstd/sync/once.rs:340
  11: coaster_nn::frameworks::cuda::<impl coaster_nn::plugin::ConvForwardAlgo>::find_cudnn_algo
  12: coaster_nn::frameworks::cuda::<impl coaster_nn::plugin::Convolution<T> for coaster::backend::Backend<coaster::frameworks::cuda::Cuda>>::new_convolution_config
  13: <juice::layers::common::convolution::Convolution<B> as juice::layer::ILayer<B>>::reshape
  14: <juice::layer::Layer<B>>::connect
  15: <juice::layers::container::sequential::Sequential<B>>::from_config
  16: <juice::layer::Layer<B>>::from_config
  17: <juice::solver::Solver<SolverB, B>>::from_config
  18: juice_examples::main
  19: std::rt::lang_start::{{closure}}
  20: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  21: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  22: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  23: main
  24: __libc_start_main
  25: _start
```

```
nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.67                 Driver Version: 390.67                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 105...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   49C    P0    N/A /  N/A |    459MiB /  4042MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1090      G   /usr/lib/xorg/Xorg                           458MiB |
+-----------------------------------------------------------------------------+
```

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic
```

**Comment by drahnr** [comment]
I think the last time I tried this was with driver 384.x but I'll try to check this over the weekend when I have access to my nvidia machine.

Do you by chance know which `cudnn` lib version is installed on your machine?

**Comment by drahnr** [comment]
Implementation API needed https://github.com/spearow/rust-cudnn/blob/master/cudnn-sys/src/generated.rs#L12657-L12666 is identical as far as I can see to the API described in the cudnn reference manual at https://docs.nvidia.com/deeplearning/sdk/cudnn-developer-guide/index.html#cudnnFindConvolutionForwardAlgorithm are matching.

Does the `mnist` example work flawlessly?

**Comment by lake-effect** [comment]
MNIST fails the same way. My `cudnn` version is 7 (`7.1.4.18-1+cuda9.2`).

**Comment by drahnr** [comment]
Which cuda version is installed? Are other things using the `cuda`/`cudnn` libs working fine on the same machine?
The nvidia tester is up and running and I should get some time to test that tonight.

**Comment by lake-effect** [comment]
CUDA is 9.2.148-1.

**Comment by lake-effect** [comment]
I'm seeing some incompatibilities between the CUDA driver version and the runtime, I'll see if I can resolve it.

**Comment by lake-effect** [comment]
I'm seeing some incompatibilities between the CUDA driver version and the runtime, but I was able to resolve it.

My batting average for a proper CUDA/CUDnn is pretty low :(

**Comment by drahnr** [comment]
But it's good you bring this up, I think there should be a simple rust test app just verifying versions are appropriate/matching/compatible.

**Comment by lake-effect** [comment]
I verified with https://docs.nvidia.com/cuda/cuda-samples/index.html
